app:
  port: 1490
  host: "0.0.0.0"
  device: "cpu"

model:
  model_path: "./keras_model/model.keras"
  epoch: 1
  batch_size: 32
  learning_rate: 0.003

image:
  width: 28
  height: 28
  channel: 1
  image_name: "temp_plot.png"

messangers:
  sender: "from@testdomain.com"
  receivers: "vladislav.kulakov@rt.ru"
  smtpObj: '10.26.101.78'