FROM python:3.8

ENV export LC_CTYPE=en_US.UTF-8
ENV export LC_ALL=en_US.UTF-8
ENV export LANG=en_US.UTF-8

WORKDIR /root/work

RUN apt-get update -y && apt-get install apt-utils -y
RUN apt-get -y install libgl1 libglib2.0-0 libgomp1

RUN apt-get -y install python3-pip

COPY requirements.txt .
COPY index.py .

RUN pip install --upgrade -r requirements.txt
RUN chmod +x /root/work/index.py

CMD ["python3", "/root/work/index.py"]
