# config file for prometheus

# global config
global:  # глобальные настройки
  scrape_interval: 15s  # Интервал очистки. Он сообщает Prometheus как часто очищать цели
  scrape_timeout: 10s  # как долго ждать завершения очистки до истечения времени ожидания
  evaluation_interval: 15s  # Он сообщает, как часто следует оценивать правила
alerting:  # настройки оповещений
  alertmanagers:  # алертменеджеры
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []  # указывает Prometheus использовать диспетчер предупреждений по умолчанию
scrape_configs:
- job_name: prometheus  #  Это название работы, которую мы хотим очистить от Prometheus. Это имя будет использоваться для ссылки на задание в других частях конфигурационного файла Prometheus
  honor_timestamps: true
  scrape_interval: 15s  # Интервал очистки для задания. Этот параметр сообщает Prometheus, как часто выполнять очистку задания
  scrape_timeout: 10s  # Это тайм-аут очистки для задания. Он сообщает Prometheus, как долго ждать завершения очистки до истечения времени ожидания
  metrics_path: /metrics  # сообщает Prometheus, где найти метрики для задания
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090  # Это цель, которую мы хотим очистить с помощью Prometheus. Эта цель будет использоваться для ссылки на цель в других частях файла конфигурации Prometheus
- job_name: 'fastapi'
  scrape_interval: 10s
  metrics_path: /metrics
  static_configs:
    - targets: ['host.docker.internal:8000']  # Это цель, которую мы хотим очистить с помощью Prometheus. Эта цель будет использоваться для ссылки на цель в других частях файла конфигурации Prometheus.